# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'RottenTomatoes' do

pod 'AFNetworking', '~> 2.0'
pod 'SVProgressHUD', '~> 1.1.2'

end

target 'RottenTomatoesTests' do

end

